# Generated by Django 5.1.5 on 2026-02-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_register')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_register')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_BreakManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_in', models.DateTimeField()),
                ('break_out', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence', models.DateTimeField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Aadhar', 'Aadhar'), ('Pan', 'Pan'), ('SSC', 'SSC'), ('Photo', 'Photo'), ('Inter', 'Inter'), ('Bank_details', 'Bank_details'), ('Graduation', 'Graduation')], max_length=60)),
                ('file', models.FileField(upload_to='')),
                ('employee_documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslips', models.FileField(upload_to='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_dashboard')),
            ],
        ),
    ]
