# Generated by Django 5.1.5 on 2026-02-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_employee_dashboard_employee_breakmanagement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_dashboard',
            old_name='name',
            new_name='employee_name',
        ),
    ]
