# Generated by Django 5.1.5 on 2026-02-25 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_employee_dashboard_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_breakmanagement',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_register'),
        ),
        migrations.AlterField(
            model_name='employee_documents',
            name='employee_documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_register'),
        ),
        migrations.AlterField(
            model_name='employee_attendence',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_register'),
        ),
        migrations.AlterField(
            model_name='employee_payroll',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_register'),
        ),
        migrations.DeleteModel(
            name='Employee_dashboard',
        ),
    ]
