# Generated by Django 5.1.5 on 2026-02-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_breakmanagement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendence',
            name='attendence',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee_attendence',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
